name: Linux build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - uses: actions/checkout@v2

    - name: install libs
      run: sudo apt update && sudo apt install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: Generate project
      run: ./vendor/unix/premake/premake5 gmake

    - name: Compile project
      run: make -j14
