name: Windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { icon: '🟨', sys: mingw32, env: i686 }
          - { icon: '🟧', sys: mingw64, env: x86_64 }

    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-SDL2
          mingw-w64-${{matrix.env}}-SDL2_image
          mingw-w64-${{matrix.env}}-SDL2_ttf
          mingw-w64-${{matrix.env}}-SDL2_mixer
          mingw-w64-${{matrix.env}}-nlohmann-json

    - name: make
      run: make
