name: Windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git

      - uses: actions/checkout@v2

      - name: install libs 
        shell: msys2 {0}
        run: |
          pacman -S mingw-w64-x86_64-toolchain --noconfirm
          yes | pacman -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer
          yes | pacman -S mingw-w64-x86_64-nlohmann-json

      - name: make
        shell: msys2 {0}
        run: make
